export const SPORTS = [
  { id: 'badminton', name: 'Badminton', icon: '🏸' },
  { id: 'football', name: 'Football', icon: '⚽' },
  { id: 'tennis', name: 'Tennis', icon: '🎾' },
  { id: 'basketball', name: 'Basketball', icon: '🏀' },
  { id: 'volleyball', name: 'Volleyball', icon: '🏐' },
  { id: 'table-tennis', name: 'Table Tennis', icon: '🏓' },
  { id: 'box-cricket', name: 'Box Cricket', icon: '🏏' },
  { id: 'pickleball', name: 'Pickleball', icon: '🎯' },
];

export const CITIES = ['Mumbai', 'Pune', 'Nagpur', 'Nashik', 'Aurangabad', 'Navi Mumbai', 'Thane'];

export const MOCK_COURTS = [
  {
    id: '1',
    owner_id: 'o1',
    name: 'Smash Zone Badminton',
    description: 'Premium badminton facility with 6 professional courts, AC halls, and state-of-the-art facilities.',
    sport: 'Badminton',
    address: 'Plot 12, MIDC Road, Andheri West',
    city: 'Mumbai',
    area: 'Andheri West',
    price_per_hour: 800,
    rating: 4.8,
    total_reviews: 124,
    is_verified: true,
    is_active: true,
    is_featured: true,
    cover_image: 'https://images.pexels.com/photos/1752757/pexels-photo-1752757.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Changing Rooms', 'Parking', 'Cafeteria', 'AC Courts', 'Equipment Rental', 'Coaching'],
    policies: 'Advance booking required. No outside food. Sports shoes mandatory.',
    distance: '2.3 km',
    available_slots: 8,
  },
  {
    id: '2',
    owner_id: 'o2',
    name: 'GreenField Football',
    description: 'Full-size premium turf ground for football and box cricket, with floodlights for night games.',
    sport: 'Football',
    address: 'Turner Road, Bandra West',
    city: 'Mumbai',
    area: 'Bandra',
    price_per_hour: 1200,
    rating: 4.6,
    total_reviews: 89,
    is_verified: true,
    is_active: true,
    is_featured: true,
    cover_image: 'https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Changing Rooms', 'Parking', 'Floodlights', 'Scoreboard', 'First Aid'],
    policies: 'Minimum 10 players required. Booking cancellable 24 hours prior.',
    distance: '4.1 km',
    available_slots: 5,
  },
  {
    id: '3',
    owner_id: 'o3',
    name: 'Ace Tennis Club',
    description: 'Professional tennis courts with experienced coaches. Both hard and clay courts available.',
    sport: 'Tennis',
    address: 'Hiranandani Gardens, Powai',
    city: 'Mumbai',
    area: 'Powai',
    price_per_hour: 1500,
    rating: 4.9,
    total_reviews: 201,
    is_verified: true,
    is_active: true,
    is_featured: false,
    cover_image: 'https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Coaching', 'Showers', 'Parking', 'Pro Shop', 'Cafeteria'],
    policies: 'Members get priority booking. Non-members: 2-day advance booking.',
    distance: '8.7 km',
    available_slots: 3,
  },
  {
    id: '4',
    owner_id: 'o4',
    name: 'Slam Dunk Arena',
    description: 'Regulation basketball court with professional wooden flooring and electronic scoreboard.',
    sport: 'Basketball',
    address: 'Viman Nagar Road, Pune',
    city: 'Pune',
    area: 'Viman Nagar',
    price_per_hour: 600,
    rating: 4.5,
    total_reviews: 67,
    is_verified: true,
    is_active: true,
    is_featured: true,
    cover_image: 'https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Parking', 'Changing Rooms', 'Scoreboard', 'Water Dispenser'],
    policies: 'Strictly 5v5 only. Soft rubber shoes required.',
    distance: '1.8 km',
    available_slots: 12,
  },
  {
    id: '5',
    owner_id: 'o5',
    name: 'Court Kings Cricket',
    description: 'Modern box cricket facility with premium nets and digital scoring system.',
    sport: 'Box Cricket',
    address: 'Majiwada Junction, Thane West',
    city: 'Thane',
    area: 'Majiwada',
    price_per_hour: 700,
    rating: 4.7,
    total_reviews: 145,
    is_verified: true,
    is_active: true,
    is_featured: false,
    cover_image: 'https://images.pexels.com/photos/3628912/pexels-photo-3628912.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Parking', 'Equipment Rental', 'Cafeteria', 'Digital Scorer'],
    policies: 'Teams of 6 per side. Booking valid for 1 hour only.',
    distance: '5.2 km',
    available_slots: 6,
  },
  {
    id: '6',
    owner_id: 'o6',
    name: 'Spin & Win TT Hall',
    description: 'Olympic-grade table tennis tables in a climate-controlled environment with professional coaching.',
    sport: 'Table Tennis',
    address: 'Sector 9, Vashi',
    city: 'Navi Mumbai',
    area: 'Vashi',
    price_per_hour: 300,
    rating: 4.4,
    total_reviews: 52,
    is_verified: true,
    is_active: true,
    is_featured: false,
    cover_image: 'https://images.pexels.com/photos/8007435/pexels-photo-8007435.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['AC Hall', 'Equipment Rental', 'Coaching', 'Water Dispenser'],
    policies: 'Equipment provided. Personal bats allowed. No street shoes.',
    distance: '3.5 km',
    available_slots: 15,
  },
  {
    id: '7',
    owner_id: 'o1',
    name: 'VolleyPro Arena',
    description: 'Indoor and outdoor volleyball courts with soft sand and hard floor options.',
    sport: 'Volleyball',
    address: 'SB Road, Shivajinagar',
    city: 'Pune',
    area: 'Shivajinagar',
    price_per_hour: 500,
    rating: 4.3,
    total_reviews: 38,
    is_verified: true,
    is_active: true,
    is_featured: false,
    cover_image: 'https://images.pexels.com/photos/1277397/pexels-photo-1277397.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Parking', 'Net Setup', 'Changing Rooms'],
    policies: 'Minimum 12 players required. Outdoor courts closed in monsoon.',
    distance: '6.0 km',
    available_slots: 9,
  },
  {
    id: '8',
    owner_id: 'o2',
    name: 'Pickle Palace',
    description: 'Maharashtra\'s first dedicated pickleball facility with 4 tournament-grade courts.',
    sport: 'Pickleball',
    address: 'Kalyani Nagar, Pune',
    city: 'Pune',
    area: 'Kalyani Nagar',
    price_per_hour: 450,
    rating: 4.6,
    total_reviews: 29,
    is_verified: false,
    is_active: true,
    is_featured: false,
    cover_image: 'https://images.pexels.com/photos/5739245/pexels-photo-5739245.jpeg?auto=compress&cs=tinysrgb&w=800',
    amenities: ['Equipment Rental', 'Coaching', 'Parking', 'Cafeteria'],
    policies: 'Beginners welcome. Equipment mandatory.',
    distance: '7.3 km',
    available_slots: 10,
  },
];

export const MOCK_TOURNAMENTS = [
  {
    id: 't1',
    name: 'Maharashtra Badminton Championship',
    sport: 'Badminton',
    city: 'Mumbai',
    start_date: '2026-06-15',
    end_date: '2026-06-20',
    registration_fee: 500,
    max_teams: 32,
    prize_pool: 50000,
    status: 'upcoming',
    cover_image: 'https://images.pexels.com/photos/1752757/pexels-photo-1752757.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Annual state-level championship with top players from across Maharashtra.',
  },
  {
    id: 't2',
    name: 'Pune Football League',
    sport: 'Football',
    city: 'Pune',
    start_date: '2026-06-01',
    end_date: '2026-06-30',
    registration_fee: 2000,
    max_teams: 16,
    prize_pool: 100000,
    status: 'upcoming',
    cover_image: 'https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'League format tournament across 4 weekends with top city teams.',
  },
  {
    id: 't3',
    name: 'Box Cricket T10 Blast',
    sport: 'Box Cricket',
    city: 'Thane',
    start_date: '2026-05-25',
    end_date: '2026-05-26',
    registration_fee: 1500,
    max_teams: 12,
    prize_pool: 30000,
    status: 'upcoming',
    cover_image: 'https://images.pexels.com/photos/3628912/pexels-photo-3628912.jpeg?auto=compress&cs=tinysrgb&w=600',
    description: 'Fast-paced box cricket with T10 format. Pure entertainment guaranteed.',
  },
];

export const MOCK_PLAYPALS = [
  {
    id: 'p1',
    player_name: 'Rahul Sharma',
    avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=100',
    sport: 'Badminton',
    skill_level: 'intermediate',
    city: 'Mumbai',
    area: 'Andheri',
    play_date: '2026-05-15',
    play_time: '07:00',
    description: 'Looking for doubles partner for morning games. Have my own racket.',
  },
  {
    id: 'p2',
    player_name: 'Priya Desai',
    avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100',
    sport: 'Tennis',
    skill_level: 'beginner',
    city: 'Mumbai',
    area: 'Bandra',
    play_date: '2026-05-16',
    play_time: '18:00',
    description: 'New to tennis, looking for patient practice partner.',
  },
  {
    id: 'p3',
    player_name: 'Vikram Nair',
    avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=100',
    sport: 'Football',
    skill_level: 'advanced',
    city: 'Pune',
    area: 'Wakad',
    play_date: '2026-05-14',
    play_time: '19:00',
    description: 'Need 3 more players for 5-a-side. Already have 7.',
  },
  {
    id: 'p4',
    player_name: 'Anjali Mehta',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100',
    sport: 'Basketball',
    skill_level: 'intermediate',
    city: 'Pune',
    area: 'Viman Nagar',
    play_date: '2026-05-17',
    play_time: '06:30',
    description: 'Weekend morning basketball sessions. 3v3 format preferred.',
  },
];

export const MOCK_REVIEWS = [
  { id: 'r1', court_id: '1', player_name: 'Amit K.', avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 5, comment: 'Fantastic courts! Very well maintained. The AC made it super comfortable even in peak summer.', created_at: '2026-04-20' },
  { id: 'r2', court_id: '1', player_name: 'Sneha R.', avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 4, comment: 'Good facility overall. Booking process was smooth. Parking can get a bit tight on weekends.', created_at: '2026-04-18' },
  { id: 'r3', court_id: '1', player_name: 'Dev P.', avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 5, comment: 'Best badminton venue in Andheri. The shuttles provided are top quality.', created_at: '2026-04-15' },
];

export const TIME_SLOTS = [
  '05:00', '06:00', '07:00', '08:00', '09:00', '10:00',
  '11:00', '12:00', '13:00', '14:00', '15:00', '16:00',
  '17:00', '18:00', '19:00', '20:00', '21:00', '22:00',
];

export const MOCK_BOOKINGS = [
  { id: 'b1', court_name: 'Smash Zone Badminton', sport: 'Badminton', booking_date: '2026-05-10', start_time: '07:00', end_time: '08:00', total_amount: 800, status: 'completed', payment_status: 'paid', cover_image: 'https://images.pexels.com/photos/1752757/pexels-photo-1752757.jpeg?auto=compress&cs=tinysrgb&w=300' },
  { id: 'b2', court_name: 'GreenField Football', sport: 'Football', booking_date: '2026-05-14', start_time: '19:00', end_time: '20:00', total_amount: 1200, status: 'confirmed', payment_status: 'paid', cover_image: 'https://images.pexels.com/photos/46798/the-ball-stadion-football-the-pitch-46798.jpeg?auto=compress&cs=tinysrgb&w=300' },
  { id: 'b3', court_name: 'Ace Tennis Club', sport: 'Tennis', booking_date: '2026-05-20', start_time: '08:00', end_time: '09:30', total_amount: 2250, status: 'pending', payment_status: 'pending', cover_image: 'https://images.pexels.com/photos/209977/pexels-photo-209977.jpeg?auto=compress&cs=tinysrgb&w=300' },
  { id: 'b4', court_name: 'Slam Dunk Arena', sport: 'Basketball', booking_date: '2026-04-28', start_time: '18:00', end_time: '19:00', total_amount: 600, status: 'cancelled', payment_status: 'refunded', cover_image: 'https://images.pexels.com/photos/1264210/pexels-photo-1264210.jpeg?auto=compress&cs=tinysrgb&w=300' },
];

export const TESTIMONIALS = [
  { id: 1, name: 'Arjun Kapoor', role: 'Regular Player', city: 'Mumbai', avatar: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=100', text: 'Book2Play completely changed how I find courts. I book my badminton slot every morning in under 30 seconds!', rating: 5 },
  { id: 2, name: 'Kavya Reddy', role: 'Football Enthusiast', city: 'Pune', avatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=100', text: 'Found amazing turf grounds through this app. The playpals feature helped me meet a whole new friend group!', rating: 5 },
  { id: 3, name: 'Rohit Joshi', role: 'Court Owner', city: 'Thane', avatar: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=100', text: 'Revenue doubled since I listed on Book2Play. Managing bookings is so easy now.', rating: 5 },
  { id: 4, name: 'Meera Singh', role: 'Tennis Player', city: 'Nagpur', avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=100', text: 'Excellent platform with genuine reviews. Never had a bad experience booking through Book2Play.', rating: 4 },
];
